#!/usr/bin/env python3
"""Turn Markdown posts into the site's static HTML.

    python3 tools/build.py            # rebuild blog/*.html and the list in blog.html
    python3 tools/build.py --serve    # rebuild, serve on :8000, and rebuild on every save

You write blog/posts/<name>.md. This writes blog/<name>.html and refreshes the
post list in blog.html. Nothing here runs on the deployed site: GitHub Pages
only ever sees plain HTML.

No installation needed — markdown2 is vendored in tools/vendor/.
"""

from __future__ import annotations

import argparse
import datetime as dt
import html
import re
import sys
import textwrap
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent / "vendor"))
import markdown2  # noqa: E402  (vendored; import must follow the path insert)

ROOT = Path(__file__).resolve().parent.parent
POSTS_DIR = ROOT / "blog" / "posts"
OUT_DIR = ROOT / "blog"
INDEX = ROOT / "blog.html"

CONTENT = ROOT / "content"
PAGES_DIR = CONTENT / "pages"
CLASSES_DIR = CONTENT / "classes"
RESEARCH_DIR = CONTENT / "research"
NOTES_DIR = ROOT / "notes"
SITE_FILE = CONTENT / "site.md"

GENERATED_BY = "Generated by tools/build.py"
LIST_START = "<!-- POSTS:START"
LIST_END = "<!-- POSTS:END -->"
WORDS_PER_MINUTE = 220

MARKDOWN_EXTRAS = [
    "fenced-code-blocks",
    "tables",
    "footnotes",
    "strike",
    "header-ids",
    "cuddled-lists",
    "smarty-pants",
]


class BuildError(Exception):
    """A problem with a post that the author needs to fix."""


# --------------------------------------------------------------- front matter

def parse_front_matter(text: str, path: Path) -> tuple[dict, str]:
    """Split a leading `---` block of `key: value` lines off the body."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise BuildError(f"{path.name}: needs a '---' front matter block at the top")

    # The closing fence is the first bare '---' after the opening one. Scanning
    # line by line rather than splitting on the string keeps a '---' further
    # down the post — inside a code block, say — from truncating the body.
    closing = next((i for i, line in enumerate(lines[1:], start=1)
                    if line.strip() == "---"), None)
    if closing is None:
        raise BuildError(f"{path.name}: front matter block is never closed with '---'")

    meta: dict[str, str | list[str]] = {}
    key = None
    for lineno, line in enumerate(lines[1:closing], start=2):
        if not line.strip():
            continue

        # An indented "- item" continues the list started by the previous key.
        item = re.match(r"\s+-\s+(.*)$", line)
        if item:
            if key is None or not isinstance(meta.get(key), list):
                raise BuildError(
                    f"{path.name} line {lineno}: a '- item' line has to sit under a "
                    f"key with nothing after its colon, like 'meta:'"
                )
            meta[key].append(_unquote(item.group(1)))
            continue

        if ":" not in line:
            raise BuildError(f"{path.name} line {lineno}: expected 'key: value', got {line!r}")
        key, value = line.split(":", 1)
        key = key.strip().lower()
        value = value.strip()
        meta[key] = _unquote(value) if value else []
    return meta, "\n".join(lines[closing + 1:]).lstrip("\n")


def _unquote(value: str) -> str:
    return value.strip().strip('"').strip("'")


# ----------------------------------------------------------------------- math
# Markdown and LaTeX fight over the same punctuation: `_` becomes emphasis, `*`
# becomes bold, `\\` gets eaten. So every math span is lifted out before the
# Markdown pass and put back afterwards, untouched. Code spans are matched too,
# but left in place — math inside a code block should stay visible as source.

_ALTERNATIVES = [
    ("code", r"```[\s\S]*?```"),
    ("code", r"`+[^`\n]+?`+"),
    ("escaped", r"\\\$"),
    ("display", r"\$\$[\s\S]+?\$\$"),
    ("display", r"\\\[[\s\S]+?\\\]"),
    ("display", r"\\begin\{(?P<env>[a-zA-Z]+\*?)\}[\s\S]+?\\end\{(?P=env)\}"),
    ("inline", r"\\\([\s\S]+?\\\)"),
    ("inline", r"\$(?!\s)(?:\\\$|[^$\n])+?(?<!\s)\$"),
]

_NAMES = [f"{kind}{i}" for i, (kind, _) in enumerate(_ALTERNATIVES)]
_SCANNER = re.compile(
    "|".join(f"(?P<{name}>{pat})" for name, (_, pat) in zip(_NAMES, _ALTERNATIVES))
)


def _token(index: int) -> str:
    # Letters and digits only: anything with an underscore or asterisk would
    # itself be reinterpreted by Markdown.
    return f"MATHSTASH{index}ENDSTASH"


def protect_math(text: str) -> tuple[str, list[tuple[str, str]]]:
    stash: list[tuple[str, str]] = []

    def replace(match: re.Match) -> str:
        for name in _NAMES:
            if match.group(name) is None:
                continue
            kind = name.rstrip("0123456789")
            if kind == "code":
                return match.group(0)  # leave code for Markdown to handle
            stash.append((kind, match.group(0)))
            return _token(len(stash) - 1)
        return match.group(0)

    return _SCANNER.sub(replace, text), stash


def restore_math(rendered: str, stash: list[tuple[str, str]]) -> str:
    """Put the math back, HTML-escaped.

    Escaping matters: `$a < b$` has to reach the browser as `&lt;`, or the parser
    treats it as the start of a tag. MathJax reads text content, so it sees `<`.
    """
    for index, (kind, raw) in enumerate(stash):
        token = _token(index)
        if kind == "escaped":
            # Keep the backslash: MathJax's processEscapes is what turns `\$`
            # into a literal dollar at display time. Emitting a bare `$` here
            # would open an inline math span in the browser instead.
            rendered = rendered.replace(token, r"\$")
            continue

        escaped = html.escape(raw, quote=False)
        if kind == "display":
            # A display equation alone in a paragraph becomes a block that can
            # scroll sideways on a narrow screen; <div> cannot live inside <p>.
            body = textwrap.indent(escaped.strip(), "  ")
            block = f'<div class="math-block">\n{body}\n</div>'
            rendered = re.sub(
                rf"<p>\s*{token}\s*</p>", lambda _m, b=block: b, rendered
            )
        rendered = rendered.replace(token, escaped)
    return rendered


# ------------------------------------------------------------------ callouts
# A blockquote whose first line is bold becomes one of the site's callout boxes:
#
#     > **One thing to watch**
#     > A bare `$` opens inline math.
#
# The block is rendered on its own and held aside as raw HTML, so Markdown does
# not get a second look at it.

CALLOUT_RE = re.compile(
    r"(?m)^> \*\*(?P<title>[^*\n]+)\*\*[ \t]*\n(?P<rest>(?:^>.*\n?)*)"
)


def extract_callouts(text: str) -> tuple[str, list[str]]:
    blocks: list[str] = []

    def replace(match: re.Match) -> str:
        rest = "\n".join(
            re.sub(r"^>[ \t]?", "", line) for line in match.group("rest").splitlines()
        )
        inner = render_markdown(rest) if rest.strip() else ""
        blocks.append(
            '<div class="callout">\n'
            f'  <p class="callout-title">{render_inline(match.group("title"))}</p>\n'
            f"{textwrap.indent(inner, '  ')}\n</div>"
        )
        return f"\nCALLOUTSTASH{len(blocks) - 1}ENDSTASH\n"

    return CALLOUT_RE.sub(replace, text), blocks


def restore_callouts(rendered: str, blocks: list[str]) -> str:
    for index, block in enumerate(blocks):
        token = f"CALLOUTSTASH{index}ENDSTASH"
        rendered = re.sub(rf"<p>\s*{token}\s*</p>", lambda _m, b=block: b, rendered)
        rendered = rendered.replace(token, block)
    return rendered


def render_markdown(body: str) -> str:
    body, callouts = extract_callouts(body)
    protected, stash = protect_math(body)
    rendered = str(markdown2.markdown(protected, extras=MARKDOWN_EXTRAS))
    rendered = restore_math(rendered, stash)
    return restore_callouts(rendered, callouts).strip()


def render_inline(text: str) -> str:
    """Render a one-line field (title, summary) — math allowed, no paragraph tags."""
    protected, stash = protect_math(text)
    rendered = str(markdown2.markdown(protected, extras=["smarty-pants"])).strip()
    if rendered.startswith("<p>") and rendered.endswith("</p>"):
        rendered = rendered[3:-4]
    return restore_math(rendered, stash)


def plain_text(text: str) -> str:
    """A version fit for <title> and <meta>: no tags, no math delimiters."""
    stripped = re.sub(r"\$\$?|\\[()\[\]]", "", text)
    stripped = re.sub(r"[*_`]", "", stripped)
    return html.escape(" ".join(stripped.split()), quote=True)


# ---------------------------------------------------------------------- posts

class Post:
    def __init__(self, path: Path):
        self.path = path
        self.slug = path.stem
        meta, body = parse_front_matter(path.read_text(encoding="utf-8"), path)

        if "title" not in meta:
            raise BuildError(f"{path.name}: front matter needs a 'title:'")
        self.title = meta["title"]
        self.summary = meta.get("summary", "")
        self.draft = meta.get("draft", "").lower() in {"true", "yes", "1"}
        self.date = self._parse_date(meta.get("date"), path)
        self.body = body
        self.body_html = render_markdown(body)
        self.minutes = self._reading_time(meta.get("reading_time"), body)

    @staticmethod
    def _parse_date(value: str | None, path: Path) -> dt.date:
        if not value:
            match = re.match(r"(\d{4}-\d{2}-\d{2})", path.stem)
            if not match:
                raise BuildError(
                    f"{path.name}: needs a 'date: YYYY-MM-DD', or a date at the "
                    f"start of the filename"
                )
            value = match.group(1)
        try:
            return dt.date.fromisoformat(value)
        except ValueError as exc:
            raise BuildError(f"{path.name}: bad date {value!r} — use YYYY-MM-DD") from exc

    @staticmethod
    def _reading_time(override: str | None, body: str) -> int:
        if override:
            return int(re.sub(r"\D", "", override) or 1)
        words = len(body.split())
        return max(1, round(words / WORDS_PER_MINUTE))

    @property
    def date_iso(self) -> str:
        return self.date.isoformat()

    @property
    def date_human(self) -> str:
        return f"{self.date.day} {self.date:%B %Y}"

    @property
    def out_path(self) -> Path:
        return OUT_DIR / f"{self.slug}.html"


# ------------------------------------------------------------------ templates

def site_config() -> dict:
    """Name, email and links used in the header and footer of every page."""
    defaults = {
        "name": "Reza",
        "email": "kazemi@berkeley.edu",
        "github": "https://github.com/kazemi-reza",
    }
    if SITE_FILE.exists():
        meta, _ = parse_front_matter(SITE_FILE.read_text(encoding="utf-8"), SITE_FILE)
        defaults.update({k: v for k, v in meta.items() if isinstance(v, str) and v})
    return defaults


NAV = [
    ("index.html", "About", "about"),
    ("classes.html", "Classes", "classes"),
    ("research.html", "Research", "research"),
    ("blog.html", "Blog", "blog"),
]


def shell(*, depth: int, active: str, title: str, description: str, body: str,
          source: str) -> str:
    """The chrome every page shares. `depth` is how many directories deep the
    page sits, so links and asset paths get the right number of '../'."""
    site = site_config()
    up = "../" * depth
    links = []
    for href, label, key in NAV:
        current = ' aria-current="page"' if key == active else ""
        links.append(f'      <a href="{up}{href}"{current}>{label}</a>')
    nav = "\n".join(links)

    return f"""<!doctype html>
<html lang="en">
<head>
<!-- {GENERATED_BY} from {source} — edit that file, not this one. -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{description}">
<meta name="color-scheme" content="light dark">
<link rel="icon" href="{up}assets/favicon.svg" type="image/svg+xml">
<link rel="stylesheet" href="{up}assets/css/style.css">
<script src="{up}assets/js/site.js"></script>
<script defer id="MathJax-script" src="{up}assets/vendor/mathjax/tex-chtml.js"></script>
</head>
<body>
<a class="skip-link" href="#main">Skip to content</a>

<header class="site-header">
  <div class="wrap">
    <a class="brand" href="{up}index.html">{site["name"]}</a>
    <nav class="nav" aria-label="Primary">
{nav}
    </nav>
  </div>
</header>

<main id="main">
  <div class="wrap">

{body}

  </div>
</main>

<footer class="site-footer">
  <div class="wrap">
    <span>&copy; <span data-year>2026</span> {site["name"]}</span>
    <span><a href="{site["github"]}">GitHub</a> &middot; <a href="mailto:{site["email"]}">Email</a></span>
  </div>
</footer>
</body>
</html>
"""


ENTRY = """    <article class="entry">
      <h3><a href="blog/{slug}.html">{title_html}</a></h3>
      <p class="meta"><time datetime="{date_iso}">{date_human}</time><span>&middot;</span><span>{minutes} min</span></p>
      <p>{summary_html}</p>
    </article>"""


def render_page(post: Post) -> str:
    body = (
        '    <a class="back" href="../blog.html">&larr; All posts</a>\n\n'
        f'    <h1 class="page-title">{render_inline(post.title)}</h1>\n'
        f'    <p class="meta"><time datetime="{post.date_iso}">{post.date_human}</time>'
        f'<span>&middot;</span><span>{post.minutes} min</span></p>\n\n'
        f"{post.body_html}"
    )
    return shell(
        depth=1,
        active="blog",
        title=f"{plain_text(post.title)} — {site_config()['name']}",
        description=plain_text(post.summary),
        body=body,
        source=f"blog/posts/{post.slug}.md",
    )


def render_entry(post: Post) -> str:
    return ENTRY.format(
        slug=post.slug,
        title_html=render_inline(post.title),
        date_iso=post.date_iso,
        date_human=post.date_human,
        minutes=post.minutes,
        summary_html=render_inline(post.summary) or "&nbsp;",
    )


# ----------------------------------------------------- classes & research --

ACTIVE_STATUSES = {"in progress", "ongoing", "active", "current"}
SEASONS = {"winter": 0, "spring": 1, "summer": 2, "fall": 3, "autumn": 3}

# Keys the templates use directly; anything else in the front matter is ignored
# rather than silently rendered somewhere unexpected.
ENTRY_KEYS = {"title", "course", "term", "status", "meta", "notes", "order", "draft"}


class Entry:
    """One course or one research project."""

    def __init__(self, path: Path, kind: str):
        self.path = path
        self.kind = kind
        meta, body = parse_front_matter(path.read_text(encoding="utf-8"), path)

        if "title" not in meta:
            raise BuildError(f"{path.name}: front matter needs a 'title:'")
        self.title = meta["title"]
        self.course = meta.get("course", "")
        self.term = meta.get("term", "")
        self.status = meta.get("status", "")
        self.spans = _as_list(meta.get("meta", []), path, "meta")
        self.notes = _as_list(meta.get("notes", []), path, "notes")
        self.draft = str(meta.get("draft", "")).lower() in {"true", "yes", "1"}
        self.order = int(meta.get("order", 100) or 100)
        self.body_html = render_markdown(body)

        if kind == "class" and not self.term:
            raise BuildError(f"{path.name}: a class needs a 'term:', e.g. 'Fall 2026'")

    @property
    def heading(self) -> str:
        if self.course:
            return f"{render_inline(self.course)} &middot; {render_inline(self.title)}"
        return render_inline(self.title)

    @property
    def term_key(self) -> tuple[int, int]:
        """Sorts 'Fall 2026' after 'Spring 2026'. Unparseable terms sort last."""
        match = re.search(r"(winter|spring|summer|fall|autumn)\s+(\d{4})", self.term, re.I)
        if not match:
            return (0, 0)
        return (int(match.group(2)), SEASONS[match.group(1).lower()])

    def render(self) -> str:
        bits = []
        if self.status:
            active = " tag--active" if self.status.lower() in ACTIVE_STATUSES else ""
            bits.append(f'<span class="tag{active}">{render_inline(self.status)}</span>')
        bits += [f"<span>{render_inline(span)}</span>" for span in self.spans]

        parts = [f'    <article class="entry">', f"      <h3>{self.heading}</h3>"]
        if bits:
            parts.append('      <p class="meta">' + "".join(bits) + "</p>")
        parts.append(textwrap.indent(self.body_html, "      "))
        if self.notes:
            items = "".join(
                f"        <li>{render_inline(note)}</li>\n" for note in self.notes
            )
            parts.append(f'      <ul class="note-links">\n{items}      </ul>')
        parts.append("    </article>")
        return "\n".join(parts)


def _as_list(value, path: Path, key: str) -> list[str]:
    if isinstance(value, list):
        return value
    if not value:
        return []
    raise BuildError(
        f"{path.name}: '{key}:' takes a list — put nothing after the colon and "
        f"write each item on its own indented '- ' line"
    )


def load_entries(directory: Path, kind: str) -> tuple[list[Entry], list[Entry]]:
    if not directory.is_dir():
        return [], []
    live, drafts = [], []
    for path in sorted(directory.glob("*.md")):
        if path.name.startswith("_"):
            continue
        entry = Entry(path, kind)
        (drafts if entry.draft else live).append(entry)
    return live, drafts


# ------------------------------------------------------------------- pages --

class PageSource:
    """content/pages/*.md — the title, the lede, and any closing prose."""

    def __init__(self, path: Path):
        self.path = path
        meta, body = parse_front_matter(path.read_text(encoding="utf-8"), path)
        if "title" not in meta:
            raise BuildError(f"{path.name}: front matter needs a 'title:'")
        self.meta = meta
        self.title = meta["title"]
        self.lede = meta.get("lede", "")
        self.description = meta.get("description", self.lede)
        self.body_html = render_markdown(body)


def read_page(name: str) -> PageSource:
    path = PAGES_DIR / f"{name}.md"
    if not path.exists():
        raise BuildError(f"missing {path.relative_to(ROOT)}")
    return PageSource(path)


def heading_block(page: PageSource) -> str:
    out = [f'    <h1 class="page-title">{render_inline(page.title)}</h1>']
    if page.lede:
        out.append(f'    <p class="lede">{render_inline(page.lede)}</p>')
    return "\n".join(out)


CARDS = [
    ("classes.html", "Classes &amp; Notes",
     "Coursework by term, with the typed notes I kept for each one."),
    ("research.html", "Research",
     "Projects I&rsquo;m working on, each with a short description of the problem."),
    ("blog.html", "Blog",
     "Longer write-ups, derivations, and things I wanted to explain to myself."),
]


def render_home(page: PageSource) -> str:
    role = page.meta.get("role", "")
    links = _as_list(page.meta.get("links", []), page.path, "links")

    parts = ['    <section class="hero">']
    if role:
        parts.append(f'      <p class="hero-role">{render_inline(role)}</p>')
    parts.append(f'      <h1 class="page-title">{render_inline(page.title)}</h1>')
    parts.append("    </section>\n")
    parts.append('    <div class="bio">')
    parts.append(textwrap.indent(page.body_html, "      "))
    if links:
        items = "".join(f"        <li>{render_inline(link)}</li>\n" for link in links)
        parts.append(f'\n      <ul class="links">\n{items}      </ul>')
    parts.append("    </div>\n")

    cards = "".join(
        f'      <li>\n        <a class="card" href="{href}">\n'
        f"          <h3>{name}</h3>\n          <p>{blurb}</p>\n"
        f"        </a>\n      </li>\n"
        for href, name, blurb in CARDS
    )
    parts.append("    <hr>\n")
    parts.append("    <h2>Elsewhere on this site</h2>")
    parts.append(f'    <ul class="tabs">\n{cards}    </ul>')
    return "\n".join(parts)


def render_classes(page: PageSource, entries: list[Entry]) -> str:
    parts = [heading_block(page)]

    terms: dict[str, list[Entry]] = {}
    for entry in sorted(entries, key=lambda e: (e.term_key, -e.order), reverse=True):
        terms.setdefault(entry.term, []).append(entry)

    for term, group in terms.items():
        # "— in progress" is derived, not typed into every file, so it cannot go
        # stale and does not leak into the summary table below.
        ongoing = any(e.status.lower() in ACTIVE_STATUSES for e in group)
        label = render_inline(term) + (" &mdash; in progress" if ongoing else "")
        parts.append(f"\n    <h2>{label}</h2>\n")
        parts.extend(entry.render() for entry in group)

    if entries:
        rows = []
        for entry in (e for group in terms.values() for e in group):
            note = render_inline(entry.notes[0]) if entry.notes else "&mdash;"
            rows.append(
                f"          <tr><td>{render_inline(entry.term)}</td>"
                f"<td>{render_inline(entry.course) or '&mdash;'}</td>"
                f"<td>{render_inline(entry.title)}</td><td>{note}</td></tr>"
            )
        parts.append(f"""
    <hr>

    <h2>At a glance</h2>
    <div class="table-scroll">
      <table>
        <thead>
          <tr><th scope="col">Term</th><th scope="col">Course</th><th scope="col">Topic</th><th scope="col">Notes</th></tr>
        </thead>
        <tbody>
{chr(10).join(rows)}
        </tbody>
      </table>
    </div>""")

    if page.body_html:
        parts.append("\n    <hr>\n")
        parts.append(textwrap.indent(page.body_html, "    "))
    return "\n".join(parts)


def render_research(page: PageSource, entries: list[Entry]) -> str:
    parts = [heading_block(page), ""]
    parts.extend(entry.render() for entry in sorted(entries, key=lambda e: (e.order, e.path.name)))
    if page.body_html:
        parts.append("\n    <hr>\n")
        parts.append(textwrap.indent(page.body_html, "    "))
    return "\n".join(parts)


class Note:
    """notes/*.md — one set of course notes."""

    def __init__(self, path: Path):
        self.path = path
        self.slug = path.stem
        meta, body = parse_front_matter(path.read_text(encoding="utf-8"), path)
        if "title" not in meta:
            raise BuildError(f"{path.name}: front matter needs a 'title:'")
        self.title = meta["title"]
        self.lede = meta.get("lede", "")
        self.draft = str(meta.get("draft", "")).lower() in {"true", "yes", "1"}
        self.body_html = render_markdown(body)

    @property
    def out_path(self) -> Path:
        return NOTES_DIR / f"{self.slug}.html"

    def render(self) -> str:
        body = ['    <a class="back" href="../classes.html">&larr; All classes</a>\n',
                f'    <h1 class="page-title">{render_inline(self.title)}</h1>']
        if self.lede:
            body.append(f'    <p class="lede">{render_inline(self.lede)}</p>')
        body.append("")
        body.append(self.body_html)
        return shell(
            depth=1,
            active="classes",
            title=f"{plain_text(self.title)} — {site_config()['name']}",
            description=plain_text(self.lede or self.title),
            body="\n".join(body),
            source=f"notes/{self.slug}.md",
        )


def update_index(posts: list[Post]) -> bool:
    """Rewrite the post list in blog.html, leaving the rest of the page alone."""
    text = INDEX.read_text(encoding="utf-8")
    start = text.find(LIST_START)
    end = text.find(LIST_END)
    if start == -1 or end == -1:
        raise BuildError(
            f"blog.html is missing the {LIST_START}…{LIST_END} markers that say "
            f"where the post list goes"
        )

    head = text[: text.index("\n", start) + 1]
    entries = "\n\n".join(render_entry(p) for p in posts) or "    <p>No posts yet.</p>"
    updated = head + "\n" + entries + "\n\n" + text[end:]
    if updated == text:
        return False
    INDEX.write_text(updated, encoding="utf-8")
    return True


def sweep_orphans(directory: Path, live: set[Path]) -> list[Path]:
    """Delete generated pages whose Markdown source is gone. Hand-written pages
    carry no generated marker, so they are never touched."""
    removed = []
    for page in sorted(directory.glob("*.html")):
        if page in live:
            continue
        if GENERATED_BY in page.read_text(encoding="utf-8"):
            page.unlink()
            removed.append(page)
    return removed


def write_if_changed(path: Path, text: str, say) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    say(f"  wrote  {path.relative_to(ROOT)}")
    return True


def build(quiet: bool = False) -> int:
    def say(message: str) -> None:
        if not quiet:
            print(message)

    if not POSTS_DIR.is_dir():
        raise BuildError(f"no posts directory at {POSTS_DIR.relative_to(ROOT)}")

    written = 0
    drafts: list[str] = []

    # ---- blog posts ------------------------------------------------------
    posts, post_drafts = [], []
    for path in sorted(POSTS_DIR.glob("*.md")):
        if path.name.startswith("_"):
            continue  # _template.md and friends
        post = Post(path)
        (post_drafts if post.draft else posts).append(post)
    posts.sort(key=lambda p: (p.date, p.slug), reverse=True)
    drafts += [f"blog/posts/{p.path.name}" for p in post_drafts]

    for post in posts:
        written += write_if_changed(post.out_path, render_page(post), say)
    for page in sweep_orphans(OUT_DIR, {p.out_path for p in posts}):
        say(f"  removed {page.relative_to(ROOT)} (no longer published)")
    if update_index(posts):
        say("  wrote  blog.html (post list)")

    # ---- course notes ----------------------------------------------------
    notes, note_drafts = [], []
    for path in sorted(NOTES_DIR.glob("*.md")) if NOTES_DIR.is_dir() else []:
        if path.name.startswith("_"):
            continue
        note = Note(path)
        (note_drafts if note.draft else notes).append(note)
    drafts += [f"notes/{n.path.name}" for n in note_drafts]

    for note in notes:
        written += write_if_changed(note.out_path, note.render(), say)
    for page in sweep_orphans(NOTES_DIR, {n.out_path for n in notes}):
        say(f"  removed {page.relative_to(ROOT)} (no longer published)")

    # ---- the three standing pages ---------------------------------------
    classes, class_drafts = load_entries(CLASSES_DIR, "class")
    research, research_drafts = load_entries(RESEARCH_DIR, "research")
    drafts += [f"content/classes/{e.path.name}" for e in class_drafts]
    drafts += [f"content/research/{e.path.name}" for e in research_drafts]

    home = read_page("index")
    written += write_if_changed(ROOT / "index.html", shell(
        depth=0, active="about",
        title=f"{site_config()['name']} — {plain_text(home.meta.get('tab_title', 'About'))}",
        description=plain_text(home.description),
        body=render_home(home), source="content/pages/index.md"), say)

    classes_page = read_page("classes")
    written += write_if_changed(ROOT / "classes.html", shell(
        depth=0, active="classes",
        title=f"{plain_text(classes_page.title)} — {site_config()['name']}",
        description=plain_text(classes_page.description),
        body=render_classes(classes_page, classes),
        source="content/pages/classes.md"), say)

    research_page = read_page("research")
    written += write_if_changed(ROOT / "research.html", shell(
        depth=0, active="research",
        title=f"{plain_text(research_page.title)} — {site_config()['name']}",
        description=plain_text(research_page.description),
        body=render_research(research_page, research),
        source="content/pages/research.md"), say)

    for draft in drafts:
        say(f"  draft  {draft} — not published "
            f"(remove 'draft: true' to publish it)")

    say(f"{len(posts)} post{'s' if len(posts) != 1 else ''}, {len(notes)} note page"
        f"{'s' if len(notes) != 1 else ''}, {len(classes)} class"
        f"{'es' if len(classes) != 1 else ''}, {len(research)} project"
        f"{'s' if len(research) != 1 else ''}; {written} file"
        f"{'s' if written != 1 else ''} rebuilt"
        + (f", {len(drafts)} held back as draft{'s' if len(drafts) != 1 else ''}" if drafts else ""))
    return len(posts)


# ---------------------------------------------------------------------- serve

def serve(port: int) -> None:
    import functools
    import http.server
    import socketserver
    import threading
    import time

    def snapshot() -> dict:
        watched = [Path(__file__)]
        for folder in (POSTS_DIR, NOTES_DIR, PAGES_DIR, CLASSES_DIR, RESEARCH_DIR, CONTENT):
            if folder.is_dir():
                watched += list(folder.glob("*.md"))
        return {p: p.stat().st_mtime for p in watched if p.exists()}

    def watch() -> None:
        last = snapshot()
        while True:
            time.sleep(0.5)
            current = snapshot()
            if current == last:
                continue
            last = current
            print("\nchange detected — rebuilding")
            try:
                build()
            except BuildError as exc:
                print(f"  error: {exc}")

    threading.Thread(target=watch, daemon=True).start()

    handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=str(ROOT))
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(("127.0.0.1", port), handler) as httpd:
        print(f"\nserving http://127.0.0.1:{port}/blog.html — Ctrl-C to stop")
        print("editing a post rebuilds it; refresh the browser to see it\n")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nstopped")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--serve", action="store_true",
                        help="rebuild, then serve locally and rebuild on every save")
    parser.add_argument("--port", type=int, default=8000, help="port for --serve (default 8000)")
    args = parser.parse_args()

    try:
        build()
    except BuildError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.serve:
        serve(args.port)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
