#!/usr/bin/env python3
"""Turn Markdown posts into the site's static HTML.

    python3 tools/build.py            # rebuild blog/*.html and the list in blog.html
    python3 tools/build.py --serve    # rebuild, serve on :8000, and rebuild on every save

You write blog/posts/<name>.md. This writes blog/<name>.html and refreshes the
post list in blog.html. Nothing here runs on the deployed site: GitHub Pages
only ever sees plain HTML.

No installation needed — markdown2 is vendored in tools/vendor/.
"""

from __future__ import annotations

import argparse
import datetime as dt
import html
import re
import sys
import textwrap
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent / "vendor"))
import markdown2  # noqa: E402  (vendored; import must follow the path insert)

ROOT = Path(__file__).resolve().parent.parent
POSTS_DIR = ROOT / "blog" / "posts"
OUT_DIR = ROOT / "blog"
INDEX = ROOT / "blog.html"

GENERATED_BY = "Generated by tools/build.py"
LIST_START = "<!-- POSTS:START"
LIST_END = "<!-- POSTS:END -->"
WORDS_PER_MINUTE = 220

MARKDOWN_EXTRAS = [
    "fenced-code-blocks",
    "tables",
    "footnotes",
    "strike",
    "header-ids",
    "cuddled-lists",
    "smarty-pants",
]


class BuildError(Exception):
    """A problem with a post that the author needs to fix."""


# --------------------------------------------------------------- front matter

def parse_front_matter(text: str, path: Path) -> tuple[dict, str]:
    """Split a leading `---` block of `key: value` lines off the body."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise BuildError(f"{path.name}: needs a '---' front matter block at the top")

    # The closing fence is the first bare '---' after the opening one. Scanning
    # line by line rather than splitting on the string keeps a '---' further
    # down the post — inside a code block, say — from truncating the body.
    closing = next((i for i, line in enumerate(lines[1:], start=1)
                    if line.strip() == "---"), None)
    if closing is None:
        raise BuildError(f"{path.name}: front matter block is never closed with '---'")

    meta: dict[str, str] = {}
    for lineno, line in enumerate(lines[1:closing], start=2):
        if not line.strip():
            continue
        if ":" not in line:
            raise BuildError(f"{path.name} line {lineno}: expected 'key: value', got {line!r}")
        key, value = line.split(":", 1)
        meta[key.strip().lower()] = value.strip().strip('"').strip("'")
    return meta, "\n".join(lines[closing + 1:]).lstrip("\n")


# ----------------------------------------------------------------------- math
# Markdown and LaTeX fight over the same punctuation: `_` becomes emphasis, `*`
# becomes bold, `\\` gets eaten. So every math span is lifted out before the
# Markdown pass and put back afterwards, untouched. Code spans are matched too,
# but left in place — math inside a code block should stay visible as source.

_ALTERNATIVES = [
    ("code", r"```[\s\S]*?```"),
    ("code", r"`+[^`\n]+?`+"),
    ("escaped", r"\\\$"),
    ("display", r"\$\$[\s\S]+?\$\$"),
    ("display", r"\\\[[\s\S]+?\\\]"),
    ("display", r"\\begin\{(?P<env>[a-zA-Z]+\*?)\}[\s\S]+?\\end\{(?P=env)\}"),
    ("inline", r"\\\([\s\S]+?\\\)"),
    ("inline", r"\$(?!\s)(?:\\\$|[^$\n])+?(?<!\s)\$"),
]

_NAMES = [f"{kind}{i}" for i, (kind, _) in enumerate(_ALTERNATIVES)]
_SCANNER = re.compile(
    "|".join(f"(?P<{name}>{pat})" for name, (_, pat) in zip(_NAMES, _ALTERNATIVES))
)


def _token(index: int) -> str:
    # Letters and digits only: anything with an underscore or asterisk would
    # itself be reinterpreted by Markdown.
    return f"MATHSTASH{index}ENDSTASH"


def protect_math(text: str) -> tuple[str, list[tuple[str, str]]]:
    stash: list[tuple[str, str]] = []

    def replace(match: re.Match) -> str:
        for name in _NAMES:
            if match.group(name) is None:
                continue
            kind = name.rstrip("0123456789")
            if kind == "code":
                return match.group(0)  # leave code for Markdown to handle
            stash.append((kind, match.group(0)))
            return _token(len(stash) - 1)
        return match.group(0)

    return _SCANNER.sub(replace, text), stash


def restore_math(rendered: str, stash: list[tuple[str, str]]) -> str:
    """Put the math back, HTML-escaped.

    Escaping matters: `$a < b$` has to reach the browser as `&lt;`, or the parser
    treats it as the start of a tag. MathJax reads text content, so it sees `<`.
    """
    for index, (kind, raw) in enumerate(stash):
        token = _token(index)
        if kind == "escaped":
            # Keep the backslash: MathJax's processEscapes is what turns `\$`
            # into a literal dollar at display time. Emitting a bare `$` here
            # would open an inline math span in the browser instead.
            rendered = rendered.replace(token, r"\$")
            continue

        escaped = html.escape(raw, quote=False)
        if kind == "display":
            # A display equation alone in a paragraph becomes a block that can
            # scroll sideways on a narrow screen; <div> cannot live inside <p>.
            body = textwrap.indent(escaped.strip(), "  ")
            block = f'<div class="math-block">\n{body}\n</div>'
            rendered = re.sub(
                rf"<p>\s*{token}\s*</p>", lambda _m, b=block: b, rendered
            )
        rendered = rendered.replace(token, escaped)
    return rendered


# ------------------------------------------------------------------ callouts
# A blockquote whose first line is bold becomes one of the site's callout boxes:
#
#     > **One thing to watch**
#     > A bare `$` opens inline math.
#
# The block is rendered on its own and held aside as raw HTML, so Markdown does
# not get a second look at it.

CALLOUT_RE = re.compile(
    r"(?m)^> \*\*(?P<title>[^*\n]+)\*\*[ \t]*\n(?P<rest>(?:^>.*\n?)*)"
)


def extract_callouts(text: str) -> tuple[str, list[str]]:
    blocks: list[str] = []

    def replace(match: re.Match) -> str:
        rest = "\n".join(
            re.sub(r"^>[ \t]?", "", line) for line in match.group("rest").splitlines()
        )
        inner = render_markdown(rest) if rest.strip() else ""
        blocks.append(
            '<div class="callout">\n'
            f'  <p class="callout-title">{render_inline(match.group("title"))}</p>\n'
            f"{textwrap.indent(inner, '  ')}\n</div>"
        )
        return f"\nCALLOUTSTASH{len(blocks) - 1}ENDSTASH\n"

    return CALLOUT_RE.sub(replace, text), blocks


def restore_callouts(rendered: str, blocks: list[str]) -> str:
    for index, block in enumerate(blocks):
        token = f"CALLOUTSTASH{index}ENDSTASH"
        rendered = re.sub(rf"<p>\s*{token}\s*</p>", lambda _m, b=block: b, rendered)
        rendered = rendered.replace(token, block)
    return rendered


def render_markdown(body: str) -> str:
    body, callouts = extract_callouts(body)
    protected, stash = protect_math(body)
    rendered = str(markdown2.markdown(protected, extras=MARKDOWN_EXTRAS))
    rendered = restore_math(rendered, stash)
    return restore_callouts(rendered, callouts).strip()


def render_inline(text: str) -> str:
    """Render a one-line field (title, summary) — math allowed, no paragraph tags."""
    protected, stash = protect_math(text)
    rendered = str(markdown2.markdown(protected, extras=["smarty-pants"])).strip()
    if rendered.startswith("<p>") and rendered.endswith("</p>"):
        rendered = rendered[3:-4]
    return restore_math(rendered, stash)


def plain_text(text: str) -> str:
    """A version fit for <title> and <meta>: no tags, no math delimiters."""
    stripped = re.sub(r"\$\$?|\\[()\[\]]", "", text)
    stripped = re.sub(r"[*_`]", "", stripped)
    return html.escape(" ".join(stripped.split()), quote=True)


# ---------------------------------------------------------------------- posts

class Post:
    def __init__(self, path: Path):
        self.path = path
        self.slug = path.stem
        meta, body = parse_front_matter(path.read_text(encoding="utf-8"), path)

        if "title" not in meta:
            raise BuildError(f"{path.name}: front matter needs a 'title:'")
        self.title = meta["title"]
        self.summary = meta.get("summary", "")
        self.draft = meta.get("draft", "").lower() in {"true", "yes", "1"}
        self.date = self._parse_date(meta.get("date"), path)
        self.body = body
        self.body_html = render_markdown(body)
        self.minutes = self._reading_time(meta.get("reading_time"), body)

    @staticmethod
    def _parse_date(value: str | None, path: Path) -> dt.date:
        if not value:
            match = re.match(r"(\d{4}-\d{2}-\d{2})", path.stem)
            if not match:
                raise BuildError(
                    f"{path.name}: needs a 'date: YYYY-MM-DD', or a date at the "
                    f"start of the filename"
                )
            value = match.group(1)
        try:
            return dt.date.fromisoformat(value)
        except ValueError as exc:
            raise BuildError(f"{path.name}: bad date {value!r} — use YYYY-MM-DD") from exc

    @staticmethod
    def _reading_time(override: str | None, body: str) -> int:
        if override:
            return int(re.sub(r"\D", "", override) or 1)
        words = len(body.split())
        return max(1, round(words / WORDS_PER_MINUTE))

    @property
    def date_iso(self) -> str:
        return self.date.isoformat()

    @property
    def date_human(self) -> str:
        return f"{self.date.day} {self.date:%B %Y}"

    @property
    def out_path(self) -> Path:
        return OUT_DIR / f"{self.slug}.html"


# ------------------------------------------------------------------ templates

PAGE = """<!doctype html>
<html lang="en">
<head>
<!-- {generated_by} from blog/posts/{slug}.md — edit that file, not this one. -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title_plain} — Reza</title>
<meta name="description" content="{summary_plain}">
<meta name="color-scheme" content="light dark">
<link rel="icon" href="../assets/favicon.svg" type="image/svg+xml">
<link rel="stylesheet" href="../assets/css/style.css">
<script src="../assets/js/site.js"></script>
<script defer id="MathJax-script" src="../assets/vendor/mathjax/tex-chtml.js"></script>
</head>
<body>
<a class="skip-link" href="#main">Skip to content</a>

<header class="site-header">
  <div class="wrap">
    <a class="brand" href="../index.html">Reza</a>
    <nav class="nav" aria-label="Primary">
      <a href="../index.html">About</a>
      <a href="../classes.html">Classes</a>
      <a href="../research.html">Research</a>
      <a href="../blog.html" aria-current="page">Blog</a>
    </nav>
  </div>
</header>

<main id="main">
  <div class="wrap">

    <a class="back" href="../blog.html">&larr; All posts</a>

    <h1 class="page-title">{title_html}</h1>
    <p class="meta"><time datetime="{date_iso}">{date_human}</time><span>&middot;</span><span>{minutes} min</span></p>

{body_html}

  </div>
</main>

<footer class="site-footer">
  <div class="wrap">
    <span>&copy; <span data-year>2026</span> Reza</span>
    <span><a href="https://github.com/rezakaze">GitHub</a> &middot; <a href="mailto:mhmdrzkzm04@gmail.com">Email</a></span>
  </div>
</footer>
</body>
</html>
"""

ENTRY = """    <article class="entry">
      <h3><a href="blog/{slug}.html">{title_html}</a></h3>
      <p class="meta"><time datetime="{date_iso}">{date_human}</time><span>&middot;</span><span>{minutes} min</span></p>
      <p>{summary_html}</p>
    </article>"""


def render_page(post: Post) -> str:
    return PAGE.format(
        generated_by=GENERATED_BY,
        slug=post.slug,
        title_plain=plain_text(post.title),
        summary_plain=plain_text(post.summary),
        title_html=render_inline(post.title),
        date_iso=post.date_iso,
        date_human=post.date_human,
        minutes=post.minutes,
        body_html=post.body_html,
    )


def render_entry(post: Post) -> str:
    return ENTRY.format(
        slug=post.slug,
        title_html=render_inline(post.title),
        date_iso=post.date_iso,
        date_human=post.date_human,
        minutes=post.minutes,
        summary_html=render_inline(post.summary) or "&nbsp;",
    )


def update_index(posts: list[Post]) -> bool:
    """Rewrite the post list in blog.html, leaving the rest of the page alone."""
    text = INDEX.read_text(encoding="utf-8")
    start = text.find(LIST_START)
    end = text.find(LIST_END)
    if start == -1 or end == -1:
        raise BuildError(
            f"blog.html is missing the {LIST_START}…{LIST_END} markers that say "
            f"where the post list goes"
        )

    head = text[: text.index("\n", start) + 1]
    entries = "\n\n".join(render_entry(p) for p in posts) or "    <p>No posts yet.</p>"
    updated = head + "\n" + entries + "\n\n" + text[end:]
    if updated == text:
        return False
    INDEX.write_text(updated, encoding="utf-8")
    return True


def sweep_orphans(live: set[Path]) -> list[Path]:
    """Delete generated pages whose Markdown source is gone. Hand-written pages
    have no generated marker, so they are never touched."""
    removed = []
    for page in sorted(OUT_DIR.glob("*.html")):
        if page in live:
            continue
        if GENERATED_BY in page.read_text(encoding="utf-8"):
            page.unlink()
            removed.append(page)
    return removed


def build(quiet: bool = False) -> int:
    def say(message: str) -> None:
        if not quiet:
            print(message)

    if not POSTS_DIR.is_dir():
        raise BuildError(f"no posts directory at {POSTS_DIR.relative_to(ROOT)}")

    posts, drafts = [], []
    for path in sorted(POSTS_DIR.glob("*.md")):
        if path.name.startswith("_"):
            continue  # _template.md and friends
        post = Post(path)
        (drafts if post.draft else posts).append(post)

    posts.sort(key=lambda p: (p.date, p.slug), reverse=True)

    written = 0
    for post in posts:
        page = render_page(post)
        if not post.out_path.exists() or post.out_path.read_text(encoding="utf-8") != page:
            post.out_path.write_text(page, encoding="utf-8")
            say(f"  wrote  blog/{post.out_path.name}")
            written += 1

    for page in sweep_orphans({p.out_path for p in posts}):
        say(f"  removed blog/{page.name} (no longer published)")

    if update_index(posts):
        say("  wrote  blog.html (post list)")

    for draft in drafts:
        say(f"  draft  blog/posts/{draft.path.name} — not published "
            f"(remove 'draft: true' to publish it)")

    say(f"{len(posts)} post{'s' if len(posts) != 1 else ''} published, {written} rebuilt"
        + (f", {len(drafts)} held back as draft{'s' if len(drafts) != 1 else ''}" if drafts else ""))
    return len(posts)


# ---------------------------------------------------------------------- serve

def serve(port: int) -> None:
    import functools
    import http.server
    import socketserver
    import threading
    import time

    def snapshot() -> dict:
        watched = list(POSTS_DIR.glob("*.md")) + [Path(__file__)]
        return {p: p.stat().st_mtime for p in watched if p.exists()}

    def watch() -> None:
        last = snapshot()
        while True:
            time.sleep(0.5)
            current = snapshot()
            if current == last:
                continue
            last = current
            print("\nchange detected — rebuilding")
            try:
                build()
            except BuildError as exc:
                print(f"  error: {exc}")

    threading.Thread(target=watch, daemon=True).start()

    handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=str(ROOT))
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(("127.0.0.1", port), handler) as httpd:
        print(f"\nserving http://127.0.0.1:{port}/blog.html — Ctrl-C to stop")
        print("editing a post rebuilds it; refresh the browser to see it\n")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nstopped")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--serve", action="store_true",
                        help="rebuild, then serve locally and rebuild on every save")
    parser.add_argument("--port", type=int, default=8000, help="port for --serve (default 8000)")
    args = parser.parse_args()

    try:
        build()
    except BuildError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.serve:
        serve(args.port)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
